apiVersion: v1
kind: Service
metadata:
  name: device-tracker-service
spec:
  type: LoadBalancer  
  ports:
    - port: 8000  
      targetPort: 8000 
      nodePort: 30007  
      protocol: TCP
  selector:
    app: device-tracker
